# Generated by Django 5.2.5 on 2025-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('bills', 'Bills'), ('utilities', 'Utilities'), ('rent/mortgage', 'Rent/Mortgage'), ('entertainment', 'Entertainment'), ('dining', 'Dining'), ('misc', 'Misc')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paid_by', models.CharField(max_length=100)),
            ],
        ),
    ]
